services:
  comfyui:
    image: ghcr.io/therepos/kasm-images/comfyui:latest
    container_name: comfyui
    ports:
      - "3030:8188"
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    shm_size: 2g
    runtime: nvidia
    restart: unless-stopped
    volumes:
      - /mnt/sec/media/shared/comfyui:/data